### ISSUE TITLE
The connection has timed out

### ISSUE THREAD

**Issue by RayBB** [hayabhay/whisper-ui#30] opened 2023-02-20 10:10 UTC
After #29 was resolved and I was able to install things I still haven't been able to actually get the UI working.
When I click the link to open the local IP address I get `The connection has timed out`. This happens both locally on my mac (with docker) and in gitpod (without docker).

I don't see any error messages.
Any pointers on debugging?

If you want to try in gitpod you can at https://gitpod.io/?editor=code#https://github.com/hayabhay/whisper-ui
Just make sure to install ffmpeg

**Comment by hayabhay** [comment] 2023-02-21 03:40
On Gitpod I tried it and it ran fine. 

Since it already spins up a container (and looks like it also installs packages from `requirements.txt`), I simply ran `streamlit run app/01_🏠_Home.py` and downloaded a video from YouTube.
(python version was 3.8)

If you got a connection timed out error, it could very likely be network issues during that time. Or, the video may have been too long. Do you know how long it was?

**Comment by hayabhay** [comment] 2023-02-26 05:32
Closing this since it couldn't be reproduced. Feel free to re-open if things change.

**Closed by hayabhay** 2023-02-26 05:32 UTC

**Comment by RayBB** [comment] 2023-02-26 12:46
confirmed it's working now
