### ISSUE TITLE
Issue when running with docker

### ISSUE THREAD

**Issue by RayBB** [hayabhay/whisper-ui#29] opened 2023-02-19 23:38 UTC
Hey y'all thanks so much for making this. It looks really great and will be helpful for my studies.

When I run `docker-compose up` it exits with the following error:

```
 => ERROR [6/7] RUN pip install --no-cache-dir -r /requirements.txt                                                  20.7s
------
 > [6/7] RUN pip install --no-cache-dir -r /requirements.txt:
#0 0.573 Collecting openai-whisper==20230124
#0 0.694   Downloading openai-whisper-20230124.tar.gz (1.2 MB)
#0 1.002      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 3.8 MB/s eta 0:00:00
#0 1.059   Preparing metadata (setup.py): started
#0 1.410   Preparing metadata (setup.py): finished with status 'done'
#0 1.449 Collecting pytube==12.1.2
#0 1.473   Downloading pytube-12.1.2-py3-none-any.whl (57 kB)
#0 1.489      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 3.6 MB/s eta 0:00:00
#0 1.726 Collecting SQLAlchemy==2.0.3
#0 1.772   Downloading SQLAlchemy-2.0.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (2.8 MB)
#0 4.235      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 1.2 MB/s eta 0:00:00
#0 4.313 Collecting streamlit==1.18.1
#0 4.337   Downloading streamlit-1.18.1-py2.py3-none-any.whl (9.6 MB)
#0 8.298      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 2.4 MB/s eta 0:00:00
#0 8.548 Collecting numpy
#0 8.575   Downloading numpy-1.24.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.0 MB)
#0 20.32      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 1.1 MB/s eta 0:00:00
#0 20.41 ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
#0 20.41 ERROR: Could not find a version that satisfies the requirement torch (from openai-whisper) (from versions: none)
#0 20.41 ERROR: No matching distribution found for torch
------
failed to solve: executor failed running [/bin/sh -c pip install --no-cache-dir -r /requirements.txt]: exit code: 1
```

This could possibly be related to me running with an M1 mac?

Please let me know if there is anything I can do to help debug here.

**Comment by hayabhay** [comment] 2023-02-20 00:12
Ah interesting! 

From the error this looks like Python 3.11 is not supported. Could you try downgrading the Python version from 3.11 to 3.10 and see if that helps? If yes, I'll update the docker file.

(I've tested it on Ubuntu 22.04 and it worked fine so this is a tad confusing)

**Comment by RayBB** [comment] 2023-02-20 00:17
Downgrading to 3.10 worked like a charm!

Thanks :)

**Comment by hayabhay** [comment] 2023-02-20 00:29
Awesome! Thanks for the flag! :)

I'll update the Dockerfile

**Comment by hayabhay** [comment] 2023-02-26 05:32
Closing this since it couldn't be reproduced. Feel free to re-open if things change.

**Closed by hayabhay** 2023-02-26 05:32 UTC
